package view;

import dao.DatabaseConnection;
import dao.UserDAO;
import java.awt.Toolkit;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.User;
import model.UserType;

public class LoginScreen extends javax.swing.JFrame {

  private final UserDAO userDAO;

  public LoginScreen() {
    DatabaseConnection databaseConnection = DatabaseConnection.getInstance();
    Connection connection = databaseConnection.getConnection();

    this.userDAO = new UserDAO(connection);

    initComponents();
    setTitle("Login");
    setResizable(false);
    centerOnScreen();

    buttonLogin.addActionListener(e -> tryLogin());
    buttonCreateUser.addActionListener(e -> tryCreateUser());

  }

  private void centerOnScreen() {
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    int x = (screenSize.width - getWidth()) / 2;
    int y = (screenSize.height - getHeight()) / 2;
    setLocation(x, y);
  }

  private void tryCreateUser() {

    final String name = nameInput.getText();
    final String email = emailInput.getText();
    final String cpf = cpfInput.getText();
    final char[] password = passwordInput.getPassword();
    final char[] confirmPassword = confirmPasswordInput.getPassword();

    if (!new String(password).equals(new String(confirmPassword))) {
      JOptionPane.showMessageDialog(
          null,
          "Houve uma falha ao cadastrar o usuário.",
          "Erro",
          JOptionPane.ERROR_MESSAGE
      );
    }

    final User user = new User(name, email, cpf, UserType.BUYER);
    boolean isUserCreated = false;

    try {
      isUserCreated = userDAO.addUser(user, password);
    } catch (SQLException ex) {
      Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
    }

    if (isUserCreated) {
      JOptionPane.showMessageDialog(
          null,
          "O usuário foi cadastrada com sucesso.",
          "Sucesso",
          JOptionPane.INFORMATION_MESSAGE
      );
      return;
    }

    JOptionPane.showMessageDialog(
        null,
        "Houve uma falha ao cadastrar o usuário.",
        "Erro",
        JOptionPane.ERROR_MESSAGE
    );
  }

  private void tryLogin() {
    final String email = emailText.getText();
    final char[] password = passwordText.getPassword();

    User user = null;
    boolean isUserValid = false;

    try {
      user = userDAO.getUserByEmail(email);
      isUserValid = userDAO.validateUser(email, password);

    } catch (SQLException ex) {
      Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
    }

    if (isUserValid) {
      DashboardScreen dashboardScreen = new DashboardScreen(user);
      dashboardScreen.setVisible(true);
      dispose();
      return;
    }

    JOptionPane.showMessageDialog(
        null,
        "Houve uma falha ao autentificar o usuário.",
        "Erro",
        JOptionPane.ERROR_MESSAGE
    );
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    LoginScreenTabs = new javax.swing.JTabbedPane();
    loginTab = new javax.swing.JPanel();
    loginEmail = new javax.swing.JPanel();
    emailLabel = new javax.swing.JLabel();
    emailText = new javax.swing.JTextField();
    loginPassword = new javax.swing.JPanel();
    passwordLabel = new javax.swing.JLabel();
    passwordText = new javax.swing.JPasswordField();
    loginButton = new javax.swing.JPanel();
    buttonLogin = new javax.swing.JButton();
    createAccountTab = new javax.swing.JPanel();
    createName = new javax.swing.JPanel();
    nameLabel = new javax.swing.JLabel();
    nameInput = new javax.swing.JTextField();
    createEmail = new javax.swing.JPanel();
    createEmailLabel = new javax.swing.JLabel();
    emailInput = new javax.swing.JTextField();
    createCpf = new javax.swing.JPanel();
    createCpfLabel1 = new javax.swing.JLabel();
    cpfInput = new javax.swing.JTextField();
    createPassword = new javax.swing.JPanel();
    createPasswordLabel = new javax.swing.JLabel();
    passwordInput = new javax.swing.JPasswordField();
    createConfirmPassword = new javax.swing.JPanel();
    createConfirmPasswordLabel = new javax.swing.JLabel();
    confirmPasswordInput = new javax.swing.JPasswordField();
    createSubmitButton = new javax.swing.JPanel();
    buttonCreateUser = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Imobiliária Systems");
    setResizable(false);
    addContainerListener(new java.awt.event.ContainerAdapter() {
      public void componentAdded(java.awt.event.ContainerEvent evt) {
        formComponentAdded(evt);
      }
    });

    loginTab.setMaximumSize(new java.awt.Dimension(325, 400));
    loginTab.setMinimumSize(new java.awt.Dimension(300, 145));
    loginTab.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 20));

    loginEmail.setMinimumSize(new java.awt.Dimension(300, 75));
    loginEmail.setPreferredSize(new java.awt.Dimension(300, 75));
    loginEmail.setLayout(new java.awt.BorderLayout());

    emailLabel.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
    emailLabel.setText("Email");
    loginEmail.add(emailLabel, java.awt.BorderLayout.CENTER);

    emailText.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
    emailText.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
    emailText.setPreferredSize(new java.awt.Dimension(64, 45));
    emailText.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        emailTextActionPerformed(evt);
      }
    });
    loginEmail.add(emailText, java.awt.BorderLayout.PAGE_END);

    loginTab.add(loginEmail);

    loginPassword.setMaximumSize(new java.awt.Dimension(300, 75));
    loginPassword.setMinimumSize(new java.awt.Dimension(300, 75));
    loginPassword.setPreferredSize(new java.awt.Dimension(300, 75));
    loginPassword.setLayout(new java.awt.BorderLayout());

    passwordLabel.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
    passwordLabel.setText("Senha");
    loginPassword.add(passwordLabel, java.awt.BorderLayout.CENTER);

    passwordText.setMaximumSize(new java.awt.Dimension(300, 75));
    passwordText.setMinimumSize(new java.awt.Dimension(300, 75));
    passwordText.setName(""); // NOI18N
    passwordText.setPreferredSize(new java.awt.Dimension(65, 45));
    loginPassword.add(passwordText, java.awt.BorderLayout.PAGE_END);

    loginTab.add(loginPassword);

    loginButton.setMaximumSize(new java.awt.Dimension(300, 50));
    loginButton.setLayout(new java.awt.BorderLayout());

    buttonLogin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    buttonLogin.setText("Entrar");
    buttonLogin.setMargin(new java.awt.Insets(10, 50, 10, 50));
    buttonLogin.setMaximumSize(new java.awt.Dimension(300, 50));
    buttonLogin.setMinimumSize(new java.awt.Dimension(300, 50));
    loginButton.add(buttonLogin, java.awt.BorderLayout.CENTER);

    loginTab.add(loginButton);

    LoginScreenTabs.addTab("Entrar", loginTab);

    createAccountTab.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 20));

    createName.setMinimumSize(new java.awt.Dimension(300, 75));
    createName.setPreferredSize(new java.awt.Dimension(300, 75));

    nameLabel.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
    nameLabel.setText("Nome");
    nameLabel.setToolTipText("");
    nameLabel.setMinimumSize(new java.awt.Dimension(43, 35));
    nameLabel.setPreferredSize(new java.awt.Dimension(300, 20));
    createName.add(nameLabel);

    nameInput.setMinimumSize(new java.awt.Dimension(300, 50));
    nameInput.setPreferredSize(new java.awt.Dimension(300, 45));
    createName.add(nameInput);

    createAccountTab.add(createName);

    createEmail.setMinimumSize(new java.awt.Dimension(300, 75));
    createEmail.setPreferredSize(new java.awt.Dimension(300, 75));

    createEmailLabel.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
    createEmailLabel.setText("Email");
    createEmailLabel.setToolTipText("");
    createEmailLabel.setMinimumSize(new java.awt.Dimension(43, 35));
    createEmailLabel.setPreferredSize(new java.awt.Dimension(300, 20));
    createEmail.add(createEmailLabel);

    emailInput.setMinimumSize(new java.awt.Dimension(300, 50));
    emailInput.setPreferredSize(new java.awt.Dimension(300, 45));
    createEmail.add(emailInput);

    createAccountTab.add(createEmail);

    createCpf.setMinimumSize(new java.awt.Dimension(300, 75));
    createCpf.setPreferredSize(new java.awt.Dimension(300, 75));

    createCpfLabel1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
    createCpfLabel1.setText("CPF");
    createCpfLabel1.setToolTipText("");
    createCpfLabel1.setMinimumSize(new java.awt.Dimension(43, 35));
    createCpfLabel1.setPreferredSize(new java.awt.Dimension(300, 20));
    createCpf.add(createCpfLabel1);

    cpfInput.setMinimumSize(new java.awt.Dimension(300, 50));
    cpfInput.setPreferredSize(new java.awt.Dimension(300, 45));
    createCpf.add(cpfInput);

    createAccountTab.add(createCpf);

    createPassword.setMinimumSize(new java.awt.Dimension(300, 75));
    createPassword.setPreferredSize(new java.awt.Dimension(300, 75));

    createPasswordLabel.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
    createPasswordLabel.setText("Senha");
    createPasswordLabel.setToolTipText("");
    createPasswordLabel.setMinimumSize(new java.awt.Dimension(43, 35));
    createPasswordLabel.setPreferredSize(new java.awt.Dimension(300, 20));
    createPassword.add(createPasswordLabel);

    passwordInput.setPreferredSize(new java.awt.Dimension(300, 45));
    passwordInput.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        passwordInputActionPerformed(evt);
      }
    });
    createPassword.add(passwordInput);

    createAccountTab.add(createPassword);

    createConfirmPassword.setMinimumSize(new java.awt.Dimension(300, 75));
    createConfirmPassword.setPreferredSize(new java.awt.Dimension(300, 75));

    createConfirmPasswordLabel.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
    createConfirmPasswordLabel.setText("Confirmar senha");
    createConfirmPasswordLabel.setToolTipText("");
    createConfirmPasswordLabel.setMinimumSize(new java.awt.Dimension(43, 35));
    createConfirmPasswordLabel.setPreferredSize(new java.awt.Dimension(300, 20));
    createConfirmPassword.add(createConfirmPasswordLabel);

    confirmPasswordInput.setPreferredSize(new java.awt.Dimension(300, 45));
    createConfirmPassword.add(confirmPasswordInput);

    createAccountTab.add(createConfirmPassword);

    createSubmitButton.setLayout(new java.awt.BorderLayout(15, 15));

    buttonCreateUser.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    buttonCreateUser.setText("Criar Conta");
    buttonCreateUser.setPreferredSize(new java.awt.Dimension(148, 44));
    createSubmitButton.add(buttonCreateUser, java.awt.BorderLayout.CENTER);

    createAccountTab.add(createSubmitButton);

    LoginScreenTabs.addTab("Cadastro", createAccountTab);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(LoginScreenTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(LoginScreenTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
    // TODO add your handling code here:

  }//GEN-LAST:event_emailTextActionPerformed

  private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_passwordInputActionPerformed

  private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
    // TODO add your handling code here:
  }//GEN-LAST:event_formComponentAdded

  // <editor-fold defaultstate="collapsed" desc="Variables of all components">
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTabbedPane LoginScreenTabs;
  private javax.swing.JButton buttonCreateUser;
  private javax.swing.JButton buttonLogin;
  private javax.swing.JPasswordField confirmPasswordInput;
  private javax.swing.JTextField cpfInput;
  private javax.swing.JPanel createAccountTab;
  private javax.swing.JPanel createConfirmPassword;
  private javax.swing.JLabel createConfirmPasswordLabel;
  private javax.swing.JPanel createCpf;
  private javax.swing.JLabel createCpfLabel1;
  private javax.swing.JPanel createEmail;
  private javax.swing.JLabel createEmailLabel;
  private javax.swing.JPanel createName;
  private javax.swing.JPanel createPassword;
  private javax.swing.JLabel createPasswordLabel;
  private javax.swing.JPanel createSubmitButton;
  private javax.swing.JTextField emailInput;
  private javax.swing.JLabel emailLabel;
  private javax.swing.JTextField emailText;
  private javax.swing.JPanel loginButton;
  private javax.swing.JPanel loginEmail;
  private javax.swing.JPanel loginPassword;
  private javax.swing.JPanel loginTab;
  private javax.swing.JTextField nameInput;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JPasswordField passwordInput;
  private javax.swing.JLabel passwordLabel;
  private javax.swing.JPasswordField passwordText;
  // End of variables declaration//GEN-END:variables
  // </editor-fold>   
}
